# docker-compose.yaml
version: "3.8"

services:
  redis:
    image: redis:latest # Use the latest official Redis image
    container_name: redis-local
    ports:
      - "6379:6379" # Map port 6379 of the container to local port 6379
    volumes:
      - ./data:/data # Mount a volume for data persistence
    command: ["redis-server", "--appendonly", "yes"] # Enables persistence on disk (optional)
